analyzer:
  exclude: [build/**]

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - annotate_overrides
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - prefer_double_quotes
    - prefer_relative_imports
    - test_types_in_equals
    - unnecessary_const
    - unnecessary_new
    - unrelated_type_equality_checks
    - valid_regexps
